# Generated by Django 5.1.4 on 2025-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consign_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addconsignment',
            name='bill_no',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
